In [1]:
pip install pandas

Requirement already satisfied: pandas in c:\users\prathamesh\anaconda3\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\prathamesh\anaconda3\lib\site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\prathamesh\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\prathamesh\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\prathamesh\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\prathamesh\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd

In [6]:
data = {
    "Name" : ["Anamika", "Pratham", "Kimaya", "Mohit", "Khushi"],
    "Marks" : [90, 78, 77, 69, 85],
    "City" : ["Singapore", "Mumbai", "Dubai", "London", "Venice"]
}

df = pd.DataFrame(data)

df

      Name  Marks       City
0  Anamika     90  Singapore
1  Pratham     78     Mumbai
2   Kimaya     77      Dubai
3    Mohit     69     London
4   Khushi     85     Venice

In [8]:
df.head()

      Name  Marks       City
0  Anamika     90  Singapore
1  Pratham     78     Mumbai
2   Kimaya     77      Dubai
3    Mohit     69     London
4   Khushi     85     Venice

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   Marks   5 non-null      int64
 2   City    5 non-null      object
dtypes: int64(1), object(2)
memory usage: 252.0+ bytes

In [10]:
df.describe()

           Marks
count   5.000000
mean   79.800000
std     8.043631
min    69.000000
25%    77.000000
50%    78.000000
75%    85.000000
max    90.000000

In [11]:
df["Marks"]

0    90
1    78
2    77
3    69
4    85
Name: Marks, dtype: int64

In [13]:
df[["Name", "Marks"]]

      Name  Marks
0  Anamika     90
1  Pratham     78
2   Kimaya     77
3    Mohit     69
4   Khushi     85

In [16]:
df[df["Marks"]>75]

      Name  Marks       City
0  Anamika     90  Singapore
1  Pratham     78     Mumbai
2   Kimaya     77      Dubai
4   Khushi     85     Venice

In [20]:
df[df["City"] == "Mumbai"]

      Name  Marks    City
1  Pratham     78  Mumbai

In [21]:
df["Marks"].max()

90

In [22]:
df["Marks"].min()

69

In [23]:
df["Marks"].mean()

np.float64(79.8)

In [24]:
df["Marks"].value_counts()

Marks
90    1
78    1
77    1
69    1
85    1
Name: count, dtype: int64

In [1]:
import pandas as pd

In [2]:
data = {
    "Name": ["Asha", "Rohan", "Meena", "Kunal", "Priya", "Asha"],
    "Marks": [78, None, 90, 55, None, 78],
    "City": ["Pune", "Mumbai", None, "Delhi", "Mumbai", "Pune"]
}

df = pd.DataFrame(data)
df

    Name  Marks    City
0   Asha   78.0    Pune
1  Rohan    NaN  Mumbai
2  Meena   90.0    None
3  Kunal   55.0   Delhi
4  Priya    NaN  Mumbai
5   Asha   78.0    Pune

In [3]:
df.isnull()

    Name  Marks   City
0  False  False  False
1  False   True  False
2  False  False   True
3  False  False  False
4  False   True  False
5  False  False  False

In [4]:
df.isnull().sum()

Name     0
Marks    2
City     1
dtype: int64

In [5]:
df.dropna()

    Name  Marks   City
0   Asha   78.0   Pune
3  Kunal   55.0  Delhi
5   Asha   78.0   Pune

In [6]:
df["Marks"].fillna(df["Marks"].mean(), inplace=True)

C:\Users\PRATHAMESH\AppData\Local\Temp\ipykernel_18456\1389251290.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Marks"].fillna(df["Marks"].mean(), inplace=True)

In [7]:
df["City"].fillna("Unknown", inplace=True)

C:\Users\PRATHAMESH\AppData\Local\Temp\ipykernel_18456\4032887332.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["City"].fillna("Unknown", inplace=True)

In [8]:
df

    Name  Marks     City
0   Asha  78.00     Pune
1  Rohan  75.25   Mumbai
2  Meena  90.00  Unknown
3  Kunal  55.00    Delhi
4  Priya  75.25   Mumbai
5   Asha  78.00     Pune

In [9]:
df.drop_duplicates()

    Name  Marks     City
0   Asha  78.00     Pune
1  Rohan  75.25   Mumbai
2  Meena  90.00  Unknown
3  Kunal  55.00    Delhi
4  Priya  75.25   Mumbai

In [10]:
df = df.drop_duplicates()

In [11]:
df.columns = df.columns.str.lower()
df

    name  marks     city
0   Asha  78.00     Pune
1  Rohan  75.25   Mumbai
2  Meena  90.00  Unknown
3  Kunal  55.00    Delhi
4  Priya  75.25   Mumbai

In [12]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    5 non-null      object
 1   marks   5 non-null      float64
 2   city    5 non-null      object
dtypes: float64(1), object(2)
memory usage: 160.0+ bytes

           marks
count   5.000000
mean   74.700000
std    12.586451
min    55.000000
25%    75.250000
50%    75.250000
75%    78.000000
max    90.000000