In [1]:
pip install pandas

Requirement already satisfied: pandas in c:\users\prathamesh\anaconda3\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\prathamesh\anaconda3\lib\site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\prathamesh\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\prathamesh\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\prathamesh\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\prathamesh\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd

In [6]:
data = {
    "Name" : ["Anamika", "Pratham", "Kimaya", "Mohit", "Khushi"],
    "Marks" : [90, 78, 77, 69, 85],
    "City" : ["Singapore", "Mumbai", "Dubai", "London", "Venice"]
}

df = pd.DataFrame(data)

df

      Name  Marks       City
0  Anamika     90  Singapore
1  Pratham     78     Mumbai
2   Kimaya     77      Dubai
3    Mohit     69     London
4   Khushi     85     Venice

In [8]:
df.head()

      Name  Marks       City
0  Anamika     90  Singapore
1  Pratham     78     Mumbai
2   Kimaya     77      Dubai
3    Mohit     69     London
4   Khushi     85     Venice

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   Marks   5 non-null      int64
 2   City    5 non-null      object
dtypes: int64(1), object(2)
memory usage: 252.0+ bytes

In [10]:
df.describe()

           Marks
count   5.000000
mean   79.800000
std     8.043631
min    69.000000
25%    77.000000
50%    78.000000
75%    85.000000
max    90.000000

In [11]:
df["Marks"]

0    90
1    78
2    77
3    69
4    85
Name: Marks, dtype: int64

In [13]:
df[["Name", "Marks"]]

      Name  Marks
0  Anamika     90
1  Pratham     78
2   Kimaya     77
3    Mohit     69
4   Khushi     85

In [16]:
df[df["Marks"]>75]

      Name  Marks       City
0  Anamika     90  Singapore
1  Pratham     78     Mumbai
2   Kimaya     77      Dubai
4   Khushi     85     Venice

In [20]:
df[df["City"] == "Mumbai"]

      Name  Marks    City
1  Pratham     78  Mumbai

In [21]:
df["Marks"].max()

90

In [22]:
df["Marks"].min()

69

In [23]:
df["Marks"].mean()

np.float64(79.8)

In [24]:
df["Marks"].value_counts()

Marks
90    1
78    1
77    1
69    1
85    1
Name: count, dtype: int64